### PR TITLE
Massive changes to LibreHunt

### LINKED ISSUE #5: NixOS Desktops
Special distro case, as it comes with KDE in the installation CD but doesn't install any default desktop.

### LINKED ISSUE #6: fix desktop environments for Qubes, and Knoppix
Qubes has XFCE for the default, and and KDE/i3 for alternatives. Knoppix doesn't come only with LXDE but also KDE and GNOME

### LINKED ISSUE #27: fix feren OS details
- from mail from feren OS dev

### LINKED ISSUE #28: add mx linux
been a year since someone asked lol

### LINKED ISSUE #30: "add video codecs parameter"
feedback from email

### LINKED ISSUE #36: more librehunt feedback from mail
Good job on your site! I think one question that might be good to ask users looking for a distro is what level of access they want to non-free programs/drivers/codecs--out of the box, optional, or not allowed. Partly because some people have strong feelings on the subject and partly because it's a good thing to point out to inexperienced users so they don't pick a distro and then be confused about why for instance videos aren't working in their browser.

### LINKED ISSUE #42: maybe add elive linux?
Elive is a "different", lightweight distro using Enlightenment. The stable is very out of date (debian wheezy) but extremely polished (so best as a demo not a daily driver imo) but the beta is rock solid and looks pretty nice, especially if you're into retro stuff. :)

### LINKED ISSUE #44: Add Garuda Linux
I would think Garuda linux be a good thing to add its really a good distro

### LINKED ISSUE #47: Sabayon's website leads to a... sketchy gambling-and-games website?
The [All Distros](https://librehunt.org/distrolist) page includes [Sabayon Linux](https://en.wikipedia.org/wiki/Sabayon_Linux?useskin=vector), a now-discontinued distro which has already rebranded itself as [MocaccinoOS](https://www.mocaccino.org/). The current link that "leads" to Sabayon's now-pretty-much-dead homepage, "www.sabayon.org"...
image
is now just a very sketchy gambling site, and most of the page is in Indonesian.

### PR DESCRIPTION
**Pull request by EarldridgeJazzedPineda**
### Website changes
* Removed hard-coded numbers
* Fixed a bug in displaying the matches
* Added Linux expertise to the displayed matches
* Updated the about page
* Added Open Graph and Twitter Card tags
* Added years to news entries
### Chooser changes
* Added a question for free software (closes #36, closes #30)
* Added a question for computer architecture (futureideas.txt)
* Added a question for the method of installing packages (futureideas.txt)
### Distro database changes
* Added distros in the database:
    * Elive (closes #42)
    * Garuda Linux (closes #44)
    * MX Linux (closes #28)
* Changed the logos of some distros:
    * Fedora (changed in 2021)
    * Kali Linux
    * Kubuntu (changed in 2024)
    * Linux Lite (changed in 2018)
    * Mageia (changed in 2013)
    * Manjaro (changed in 2022)
    * Linux Mint (changed in 2021)
    * Ubuntu (changed in 2022)
    * Ubuntu Budgie (changed in 2024)
* Corrected information for some distros:
    * Feren OS (closes #27)
    * NixOS (closes #5)
    * Qubes OS (closes #6)
* Replaced Sabayon with MocaccinoOS (rebranded in 2020) (closes #47)
* Removed Chakra Linux from the database (discontinued in 2021)

### CODE REVIEW

**Comment by aviwad** [comment]
why did you close this? i'll merge it. thank you. this is great work. i must add you in the credits page

**Comment by aviwad** [comment]
How do you want credits? About page or News page? Thanks.

**Comment by aviwad** [comment]
Have removed references my now-deleted Twitter account.

**Comment by EarldridgeJazzedPineda** [comment]
I have already added a list of contributors to the about page.

**Comment by aviwad** [comment]
This is awesome. Thank you so much 😁

**Pull request merged**
