### PR TITLE
Add support for gaming

### LINKED ISSUE #37: "add gaming"
feedback from @killyourfm on twitter

### PR DESCRIPTION
**Pull request by getchoo**
Add a gaming slide to `index.html` along with support for sorting by whether or not a distro is good for gaming in `librehunt.js`. Fixes #37.

I tested this branch via httpd (apache2) on Solus with nodejs v12.15.0 and it worked perfectly.

First time messing around in html and javascript by the way, so let me know if I messed anything up too much.

### CODE REVIEW

**Comment by aviwad** [comment]
Okay, wow, that's a lot. This will take me some time to review, considering I have like 5 school projects to submit the coming weeks. Thank you for helping nonetheless! Going through a quick scroll, it looks pretty good. Where did you get the game controller icon from, as I use only Twemoji (Twitter Emoji) icons everywhere else

**Comment by sethfl** [comment]
I got the controller icon from [here](https://www.needpix.com/photo/664561/joystick-video-game-flat-material-design-x-box-xbox-technology-play-enjoy). It is under a creative commons license so it should be good, but I could use a twemoji if you prefer.

**Comment by aviwad** [comment]
exams got over a week ago, but projects + school work has killed my free time. I'll check this around end of may. thanks for the work

**Comment by aviwad** [comment]
thank you.

**Pull request merged**
